import 'package:flutter/material.dart';
import '../models/book.dart';
import '../services/api_service.dart';

class AddBookPage extends StatefulWidget {
  @override
  _AddBookPageState createState() => _AddBookPageState();
}

class _AddBookPageState extends State<AddBookPage> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _authorController = TextEditingController();
  final _genreController = TextEditingController();
  final _publishedYearController = TextEditingController();
  final _isbnController = TextEditingController();
  final _imageUrlController = TextEditingController();
  final ApiService apiService = ApiService();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Add Book'),
        backgroundColor: Colors.blue, // Mengatur warna navbar menjadi biru
                          foregroundColor: Colors.white, // Mengatur warna teks menjadi putih

      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: InputDecoration(labelText: 'Title'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a title';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _authorController,
                decoration: InputDecoration(labelText: 'Author'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter an author';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _genreController,
                decoration: InputDecoration(labelText: 'Genre'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a genre';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _publishedYearController,
                decoration: InputDecoration(labelText: 'Published Year'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a published year';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _isbnController,
                decoration: InputDecoration(labelText: 'ISBN'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter an ISBN';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _imageUrlController,
                decoration: InputDecoration(labelText: 'Image URL'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter an image URL';
                  }
                  return null;
                },
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    // Call API to add book
                    apiService.addBook(Book(
                      id: 0, // ID will be generated by the backend
                      title: _titleController.text,
                      author: _authorController.text,
                      genre: _genreController.text,
                      publishedYear: int.parse(_publishedYearController.text),
                      isbn: _isbnController.text,
                      imageUrl: _imageUrlController.text,
                    ));
                    Navigator.pop(context);
                  }
                },
                child: Text('Add Book'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.blue, // Mengatur warna tombol menjadi biru
                  foregroundColor: Colors.white, // Mengatur warna teks menjadi putih
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}